### ISSUE TITLE
`OrchardBuilderNotAvailable` when calling "shield all" or "send" following public alpha testnet instructions

### ISSUE THREAD

**Issue by miltonjonat** [willemolding/CarteZcash#38]
Hey there! Great work. I was following the [instructions](https://hackmd.io/@wollum/Sk2CyliEC) for trying out the public alpha testnet, but failed to execute operations such as `shield all` and `send`. Maybe there is something else to configure?

Here goes a full stack trace:

```
$ RUST_BACKTRACE=full zingo-cli --server https://cartezcash-fullnode.fly.dev:443 --birthday 0
2024-06-03T18:36:04.748625Z  INFO zingo_cli: data_dir: wallets
2024-06-03T18:36:04.768002Z  INFO zingolib::wallet: Reading wallet version 28
2024-06-03T18:36:04.771593Z  INFO zingolib::wallet: Keys in this wallet:
2024-06-03T18:36:04.771662Z  INFO zingolib::wallet:   - Orchard Spending Key
2024-06-03T18:36:04.771667Z  INFO zingolib::wallet:   - Sapling Extended Spending Key
2024-06-03T18:36:04.771669Z  INFO zingolib::wallet:   - transparent extended private key
2024-06-03T18:36:04.772500Z  INFO zingo_cli:
2024-06-03T18:36:04.772538Z  INFO zingo_cli: Starting Zingo-CLI
2024-06-03T18:36:04.772566Z  INFO zingo_cli: Light Client config ZingoConfig { lightwalletd_uri: RwLock { data: https://cartezcash-fullnode.fly.dev:443/, poisoned: false, .. }, chain: Mainnet, reorg_buffer_offset: 0, monitor_mempool: true, wallet_dir: Some("wallets"), wallet_name: "zingo-wallet.dat", logfile_name: "zingo-wallet.debug.log" }
2024-06-03T18:36:04.772630Z  INFO zingo_cli: Lightclient connecting to https://cartezcash-fullnode.fly.dev:443/
2024-06-03T18:36:04.773399Z  INFO zingolib::lightclient: We have trees now proceeding with sync
{
  "result": "success",
  "latest_block": 5,
  "total_blocks_synced": 0
}
(mainnet) Block:5 (type 'help') >> shield all
2024-06-03T18:36:09.979629Z  INFO zingolib::wallet::send: 0: Creating transaction sending 40000 zatoshis to 1 addresses
2024-06-03T18:36:10.013353Z  INFO zingolib::wallet::send: 1: Adding outputs
2024-06-03T18:36:10.013981Z ERROR zingolib::wallet::send: Error adding output: OrchardBuilderNotAvailable
thread '<unnamed>' panicked at zingolib/src/wallet/send.rs:312:18:
To add outputs: "Error adding output: OrchardBuilderNotAvailable"
stack backtrace:
   0:     0x55cce2e65916 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55cce2e65916 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cce2e65916 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55cce2e65916 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55cce2e94750 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x55cce2e94750 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x55cce2e61eff - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x55cce2e656f4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55cce2e656f4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55cce2e66f77 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x55cce2e66cd9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x55cce2e67408 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x55cce2e672e2 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x55cce2e65e16 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55cce2e67040 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x55cce23515e5 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x55cce2351b33 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x55cce25caefd - zingolib::wallet::send::<impl zingolib::wallet::LightWallet>::create_and_populate_tx_builder::{{closure}}::hc540c05b80fd0750
  18:     0x55cce25c643d - zingolib::wallet::send::<impl zingolib::wallet::LightWallet>::create_publication_ready_transaction::{{closure}}::h6c2384b65b398d88
  19:     0x55cce2570544 - tokio::runtime::park::CachedParkThread::block_on::h0f05bfd2591c605e
  20:     0x55cce26617a0 - tokio::runtime::runtime::Runtime::block_on::h575751b326705cb2
  21:     0x55cce2613ea4 - <zingolib::commands::ShieldCommand as zingolib::commands::Command>::exec::haa0c47567cf58284
  22:     0x55cce2617330 - zingolib::commands::do_user_command::hb0f601151f19325e
  23:     0x55cce237d502 - std::sys_common::backtrace::__rust_begin_short_backtrace::heb7f67fbec6a25c0
  24:     0x55cce237e14c - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd9b173b08e90c609
  25:     0x55cce2e6ca75 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h12de4fc57affb195
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  26:     0x55cce2e6ca75 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3c619f45059d5cf1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  27:     0x55cce2e6ca75 - std::sys::unix::thread::Thread::new::thread_start::hbac657605e4b7389
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
  28:     0x7f8ccf1fa609 - start_thread
                               at /build/glibc-wuryBv/glibc-2.31/nptl/pthread_create.c:477:8
  29:     0x7f8ccefc8353 - clone
                               at /build/glibc-wuryBv/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  30:                0x0 - <unknown>
Error executing command shield: receiving on a closed channel
2024-06-03T18:36:10.152561Z ERROR zingo_cli: Error executing command shield: receiving on a closed channel

thread 'main' panicked at zingocli/src/lib.rs:139:55:
called `Result::unwrap()` on an `Err` value: SendError { .. }
stack backtrace:
   0:     0x55cce2e65916 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55cce2e65916 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cce2e65916 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55cce2e65916 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55cce2e94750 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x55cce2e94750 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x55cce2e61eff - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x55cce2e656f4 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55cce2e656f4 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55cce2e66f77 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x55cce2e66cd9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x55cce2e67408 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x55cce2e672e2 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x55cce2e65e16 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55cce2e67040 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x55cce23515e5 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x55cce2351b33 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x55cce23599ac - zingo_cli::start_interactive::{{closure}}::h24943dfce74289f4
  18:     0x55cce235cb5e - zingo_cli::run_cli::h590f29ac7a3468cd
  19:     0x55cce2351f03 - std::sys_common::backtrace::__rust_begin_short_backtrace::he66cd1c4571047f4
  20:     0x55cce2351f19 - std::rt::lang_start::{{closure}}::he4846fe049a3a86a
  21:     0x55cce2e59c41 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  22:     0x55cce2e59c41 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  23:     0x55cce2e59c41 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  24:     0x55cce2e59c41 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  25:     0x55cce2e59c41 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  26:     0x55cce2e59c41 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  27:     0x55cce2e59c41 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  28:     0x55cce2e59c41 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  29:     0x55cce2e59c41 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  30:     0x55cce2351f75 - main
  31:     0x7f8cceecd083 - __libc_start_main
                               at /build/glibc-wuryBv/glibc-2.31/csu/../csu/libc-start.c:308:16
  32:     0x55cce2351e3e - _start
  33:                0x0 - <unknown>
```

**Comment by willemolding** [comment]
Hi, thanks for posting the issue. Would you mind running the following:
```shell
cargo uninstall zingo-cli
cargo install --git https://github.com/willemolding/zingolib --branch willem/tinycash-desktop --locked --bin zingo-cli
```

this adds the `--locked` flag to cargo install to make sure it uses the exact same versions of the dependencies as defined in the repo. I get the feeling that some weirdness is going on around that and it isn't getting the correct version of `librustzcash`

Let me know how that goes
